meta:
  version: 3
  flow: Chip
  substituting_steps:
  
    # Magic reports some overlaps which can be ignored
    Checker.IllegalOverlap: null
    # Not working correctly
    KLayout.SealRing: null
    # Disable magic DRC 
    Magic.DRC: null
    Checker.MagicDRC: null
    # Disable KLayout density check
    KLayout.Density: null
    Checker.KLayoutDensity: null


    # you can uncomment this for the flow to be faster. Comment it again in the final run.
    #KLayout.DRC: null
    #Checker.KLayoutDRC: null

    # you can uncomment this for the flow to be faster. Comment it again in the final run.
    #KLayout.Antenna: null
    #Checker.KLayoutAntenna: null
    
    # you can uncomment this for the flow to be faster. Comment it again in the final run.
    #OpenROAD.IRDropReport: null
    #KLayout.XOR: null
    #Netgen.LVS: null
    #Checker.LVS: null

    KLayout.Filler: Magic.Filler

MAGIC_FILLER_SCRIPT: dir::scripts/generate_fill.py
MAGIC_FILLER_OPTIONS: ["-keep"]

DESIGN_NAME: top

VERILOG_FILES:
- src/top.sv
- src/chipinvaders.sv
- dir::src/rtl/*.sv

USE_SLANG: true

CLOCK_PERIOD: 25
CLOCK_PORT: clk_PAD

FP_SIZING: absolute
DIE_AREA: [0, 0, 1600, 1600]
CORE_AREA: [358, 358, 1242, 1242]

PDN_CORE_RING: true
PDN_CORE_RING_CONNECT_TO_PADS: true
MAGIC_EXT_UNIQUE: "notopports"
PDN_ENABLE_PINS: false
PDN_CORE_RING_VWIDTH: 15
PDN_CORE_RING_HWIDTH: 15
PDN_CORE_RING_VSPACING: 5
PDN_CORE_RING_HSPACING: 5

VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]

GRT_ALLOW_CONGESTION: true
IGNORE_DISCONNECTED_MODULES:
- bondpad_70x70_5L
PAD_BONDPAD_NAME: bondpad_70x70_5L
EXTRA_GDS:
- dir::bondpad_5l/gds/bondpad_70x70_5L.gds
EXTRA_LEFS:
- dir::bondpad_5l/lef/bondpad_70x70_5L.lef

PAD_NORTH:
  - "vga_r_pads\\[0\\].vga_r_pad"
  - "vga_r_pads\\[1\\].vga_r_pad"
  - "vga_r_pads\\[2\\].vga_r_pad"
  - "vga_r_pads\\[3\\].vga_r_pad"
  - "vga_g_pads\\[0\\].vga_g_pad"
  - "vga_g_pads\\[1\\].vga_g_pad"
  - "vga_g_pads\\[2\\].vga_g_pad"

PAD_EAST:
  - "vga_g_pads\\[3\\].vga_g_pad"
  - "vga_b_pads\\[0\\].vga_b_pad"
  - "vga_b_pads\\[1\\].vga_b_pad"
  - "vga_b_pads\\[2\\].vga_b_pad"
  - "vga_b_pads\\[3\\].vga_b_pad"
  - "vga_hs_pad"
  - "vga_vs_pad" 

PAD_SOUTH:
  - "vdd_pads\\[0\\].vdd_pad"
  - "vss_pads\\[0\\].vss_pad"
  - "iovdd_pads\\[0\\].iovdd_pad"
  - "iovss_pads\\[0\\].iovss_pad"

PAD_WEST:
  - "clk_pad"
  - "rst_n_pad"
  - "button_left_pad"
  - "button_right_pad"
  - "button_shoot_pad"

PDN_OBSTRUCTIONS:
  - [TopMetal1, 370, 380, 570, 612]

ROUTING_OBSTRUCTIONS:
  - [TopMetal1, 370, 380, 570, 612]